### PR TITLE
Fix typo in 'llms_rest_enrollments_item_schema' hook.

### PR DESCRIPTION
**Pull request by pondermatic**

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo I'm partial to just fixing the typo and deploying with a note in the changelog. Since everything around the REST API states it's in beta and the API is subject to change I think this is okay.

Do you disagree with me? If you do the change should be made to preserve the typo in the filter -- calling both the old (typo) filter and the new (correctly spelled filter).

**Comment by pondermatic** [comment]
Dang! I made that last commit to the wrong branch.

**Comment by pondermatic** [comment]
This hook has not been part of a release yet.

**Comment by eri-trabiccolo** [comment]
@thomasplevy I agree with you as general rule (paypal docet 🥰)
And fortunately we don't have to care about this now as the typo has not been released yet as @pondermatic said 🎉

**Comment by eri-trabiccolo** [comment]
I'm not in front of my computer right now so I'm not sure about the latest commit @pondermatic
I see the parent::get_collection_params actually sets ['context']['default'] to 'view'. You might still be right with mine being just another stupid typo, but I don't remember at the moment why I did that... Will look at it tomorrow. Thanks as usual!

**Comment by pondermatic** [comment]
The extra commit 747bce4a083e34779d7f99554e7c96f230491ad1 was meant for PR #149.

**Comment by eri-trabiccolo** [comment]
Ok I see, so you can reset the latest commit and force the push on this branch I guess?!

**Comment by pondermatic** [comment]
I tried using `git revert ...` but I get an `Internal Server Error` when pushing back to github. Will this PR and PR #149 merge cleanly into the master branch?

**Comment by eri-trabiccolo** [comment]
I think so, but I would rather separate the two commits. Not sure about your issue, I'd go with:
`git reset --hard HEAD~1` to revert the latest commit, then `git push {remote} {branch} --force`.

**Comment by pondermatic** [comment]
Thank you @eri-trabiccolo! The `--force` option did the trick.

**Pull request merged**
