### PR TITLE
Users search

### LINKED ISSUE #145: Students: Allow students filtering by email address
Add `search` and `search_columns` request parameters to the LIST students endpoint (https://developer.lifterlms.com/rest-api/#tag/Students/paths/~1students/get)

These parameters should map to the underlying `WP_User_Query()` (https://developer.wordpress.org/reference/classes/WP_User_Query/prepare_query/)

### PR DESCRIPTION
**Pull request by eri-trabiccolo**
## Description
fixes #145

Aside from tests to be added, and proper docs I would like to know, if you have time @thomasplevy, your opinion on the approach, suggestions etc.

## How has this been tested?
Only manually, need to write proper unit tests, this is a wip

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code has been tested.
- [x] My code passes all existing automated tests. 
- [x] My code follows the LifterLMS Coding & Documentation Standards.

### CODE REVIEW

**Comment by thomasplevy** [comment]
This looks generally good. I didn't pull down and run. I'll look more closely tomorrow.

**Comment by eri-trabiccolo** [comment]
@thomasplevy
Not sure it was already clear, but this PR is ready to be reviewed - I mean it's not in WIP state anymore.

**Comment by thomasplevy** [comment]
@eri-trabiccolo 
I know, I've had a lot on my plate and haven't prioritized this review

**Comment by eri-trabiccolo** [comment]
Yeah, just wanted to be sure, because actually I hadn't informed you about the 'status' change of this.

**Comment by thomasplevy** [comment]
> Yeah, just wanted to be sure, because actually I hadn't informed you about the 'status' change of this.

I saw it, I just hadn't done it yet!

**Pull request merged**
