### PR TITLE
Pending Release

### PR DESCRIPTION
**Pull request by thomasplevy**
+ #244

### CODE REVIEW

**Comment by thomasplevy** [comment]
@eri-trabiccolo we'll have to bump the minimum supported version and ship a release (that we'll rope into what will become the 6.x branch of the core). Can you handle take care of these?

**Comment by eri-trabiccolo** [comment]
@thomasplevy I can do that right now if this is what you mean :D

**Comment by thomasplevy** [comment]
Not an emergency but it would be good to do. I think we could be close to shipping an alpha release later this week so this will need to be done for that.

**Comment by eri-trabiccolo** [comment]
@thomasplevy alright so, can you push a changelog for that PR if you think it needs it?

**Comment by thomasplevy** [comment]
Since you approved my PR without noting this you can write it now <3

**Pull request closed without merging**
